"""
agent/agent.py
--------------
LangGraph state machine agent with:
  - Custom BATCHED LLM router (not LangChain's built-in)
  - Critic node that validates response against PDF rules
  - Intent detection for multi-intent messages
  - Conversation state tracking for multi-turn flows
"""

import os
import uuid
import json
from typing import TypedDict, Annotated
import operator
import re
import sqlite3

from langgraph.graph import StateGraph, END

from core.llm_client import llm_call
from core.database import (
    get_global_stats, get_business_meta,
    save_conversation_state, load_conversation_state,
)
from core.logger import (
    log_message,
    log_tool_call,
    log_chunk_retrieval,
    log_agent_event,
    get_conversation_history,
)
from agent.rag_engine import (
    chunk_query_into_topics,
    retrieve_relevant_chunks,
    get_customer_context,
    build_composite_prompt,
)
from agent.tools import TOOLS


# ─────────────────────────────────────────────
# State Schema
# ─────────────────────────────────────────────

class AgentState(TypedDict):
    user_id: int
    conversation_id: str
    query: str
    history: list[dict]
    all_chunks: list[dict]
    retrieved_chunks: list[dict]
    retrieved_chunk_ids: list[int]
    query_topics: list[str]
    detected_intents: list[str]
    customer_context: dict
    global_stats: dict
    tool_results: dict
    activated_tools: list[str]
    response: str
    critic_passed: bool
    critic_feedback: str
    business_name: str
    business_type: str
    internal_plan: str  # High-level plan generated by the Planner
    conversation_state: dict  # persistent multi-turn state


# ─────────────────────────────────────────────
# Node: receive_input
# ─────────────────────────────────────────────

def node_receive_input(state: AgentState) -> AgentState:
    history = get_conversation_history(state["conversation_id"], limit=15)
    log_message(state["conversation_id"], "user", state["query"])

    # Load persistent conversation state
    conv_state = load_conversation_state(state["conversation_id"]) or {
        "active_flow": None,  # e.g. "ordering", "booking", "info"
        "pending_slots": {},  # fields still needed
        "cart_active": False,
        "last_tool": None,
        "suggestions_shown": [],  # Track session-level suggestions
    }

    return {**state, "history": history, "conversation_state": conv_state}


# ─────────────────────────────────────────────
# Node: planner
# ─────────────────────────────────────────────

def node_analyze(state: AgentState) -> AgentState:
    """
    MERGED node: detect_intents + planner + route_tools in ONE LLM call.
    Saves 2 full LLM round-trips per turn while preserving all logic.
    """
    query = state["query"]
    history_snippet = "\n".join(
        f"{m['role'].upper()}: {m['content']}" for m in state["history"][-4:]
    )
    conv_state = state.get("conversation_state", {})
    customer_tier = state.get("customer_context", {}).get("loyalty_tier", "bronze")
    pdf_context = "\n".join(
        f"- {c.get('section_title', 'Info')}: {c.get('text', '')[:120]}"
        for c in state["retrieved_chunks"][:3]
    )

    tools_list = "\n".join(
        f"  {name}: {desc}"
        for name, (_, desc) in TOOLS.items()
    )

    prompt = f"""You are the analysis engine for a customer service AI agent for "{state['business_name']}".
Analyze the customer message and return a SINGLE JSON object with three keys.

Customer query: "{query}"
Conversation history:
{history_snippet or 'None'}
Active flow: {conv_state.get('active_flow', 'none')}
Pending slots: {json.dumps(conv_state.get('pending_slots', {}))}
Customer tier: {customer_tier}
Retrieved knowledge summary:
{pdf_context or 'None'}

Available tools:
{tools_list}

Return ONLY this JSON (no markdown):
{{
  "intents": ["order_item", "ask_pricing"],
  "plan": "1. Add item to cart. 2. Confirm delivery preference.",
  "tools": ["add_to_cart", "get_pricing"]
}}

Rules:
- intents: list from [order_item, remove_item, view_cart, confirm_order, book_appointment,
  reschedule, cancel_booking, check_availability, ask_pricing, ask_hours, ask_info,
  provide_address, set_delivery, complaint, greeting, provide_missing_info,
  ask_recommendations, loyalty_question, goodbye]
- plan: concise bullet plan (max 3 bullets)
- tools: ONLY tools actually needed. Empty array [] for greetings/simple info.
- If the customer asked multiple questions (e.g. price AND booking), ensure you activate ALL relevant intents and tools.
- Do NOT activate tools unless clearly required by the query."""

    try:
        raw = llm_call(prompt, temperature=0.0, max_tokens=400,
                       conversation_id=state["conversation_id"])
        raw = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        result = json.loads(raw)
        intents = result.get("intents", ["ask_info"])
        plan = result.get("plan", "Address the customer query.")
        # FIX: Ensure unique tool activation to prevent duplicate calls causing pricing errors
        raw_activated = [t for t in result.get("tools", []) if t in TOOLS]
        activated = list(dict.fromkeys(raw_activated))
    except Exception as e:
        log_agent_event(state["conversation_id"], "analyze_error", {"error": str(e)})
        intents = ["ask_info"]
        plan = "Address the customer query using available tools and knowledge."
        activated = []

    # Log tool routing decisions
    for tool_name in TOOLS:
        activated_flag = tool_name in activated
        log_tool_call(
            state["conversation_id"],
            tool_name,
            {"query": query, "intents": intents},
            {"activated": activated_flag},
            activated=activated_flag,
        )

    log_agent_event(state["conversation_id"], "intent_detection", {"intents": intents})
    log_agent_event(state["conversation_id"], "internal_planning", {"plan": plan})
    log_agent_event(state["conversation_id"], "tool_routing", {"activated_tools": activated})

    return {
        **state,
        "detected_intents": intents,
        "internal_plan": plan,
        "activated_tools": activated,
    }


# ─────────────────────────────────────────────
# Node: rag_retrieval
# ─────────────────────────────────────────────

def node_rag_retrieval(state: AgentState) -> AgentState:
    topics = chunk_query_into_topics(state["query"], state["history"])
    log_agent_event(state["conversation_id"], "query_topics", {"topics": topics})

    retrieved_chunks, chunk_ids = retrieve_relevant_chunks(
        topics, state["all_chunks"], top_n=5
    )
    if chunk_ids:
        log_chunk_retrieval(state["conversation_id"], chunk_ids)

    customer_ctx = get_customer_context(state["user_id"], state["conversation_id"])
    global_stats = get_global_stats()

    return {
        **state,
        "query_topics": topics,
        "retrieved_chunks": retrieved_chunks,
        "retrieved_chunk_ids": chunk_ids,
        "customer_context": customer_ctx,
        "global_stats": global_stats,
    }


# ─────────────────────────────────────────────
# Node: execute_tools
# ─────────────────────────────────────────────

def node_execute_tools(state: AgentState) -> AgentState:
    tool_results: dict = {}
    
    # Priority for tool execution to avoid state race conditions:
    # 1. Modifying tools (add/remove from cart, set delivery)
    # 2. Informational/Viewing tools (view_cart, get_pricing)
    # 3. Finalizing tools (confirm_order, book_appointment)
    PRIORITY = {
        "add_to_cart": 1,
        "remove_from_cart": 1,
        "set_delivery_type": 1,
        "validate_address": 1,
        "view_cart": 2,
        "get_pricing": 2,
        "get_recommendations": 2,
        "check_availability": 2,
        "confirm_order": 9,
        "book_appointment": 9,
    }
    
    sorted_tools = sorted(
        state["activated_tools"],
        key=lambda x: PRIORITY.get(x, 5)
    )

    for tool_name in sorted_tools:
        if tool_name not in TOOLS:
            continue
        tool_fn, _ = TOOLS[tool_name]
        try:
            result = tool_fn(state)
            tool_results[tool_name] = result
            log_tool_call(
                state["conversation_id"],
                tool_name,
                {"query": state["query"]},
                result,
                activated=True,
            )
        except Exception as e:
            tool_results[tool_name] = {"success": False, "error": str(e)}
            log_agent_event(state["conversation_id"], "tool_error", {"tool": tool_name, "error": str(e)})

    # Update conversation state based on tool results
    conv_state = dict(state.get("conversation_state", {}))
    for name, result in tool_results.items():
        if name in ("add_to_cart", "remove_from_cart"):
            conv_state["cart_active"] = bool(result.get("cart_items"))
            conv_state["active_flow"] = "ordering"
        elif name == "confirm_order":
            conv_state["cart_active"] = False
            conv_state["active_flow"] = None
        elif name == "book_appointment":
            if result.get("needs_info"):
                conv_state["active_flow"] = "booking"
                conv_state["pending_slots"] = {f: True for f in result.get("missing_fields", [])}
            else:
                conv_state["active_flow"] = None
                conv_state["pending_slots"] = {}
        elif name == "validate_address":
            if result.get("success"):
                conv_state.setdefault("pending_slots", {}).pop("address", None)
        conv_state["last_tool"] = name

    # Heuristic for satisfying conversational requirements
    q_lower = state["query"].lower()
    satisfied = conv_state.setdefault("satisfied_requirements", [])
    if any(x in q_lower for x in ["no allergy", "don't have allergy", "not allergic", "no dietary"]):
        satisfied.append("allergies_checked")
    if any(x in q_lower for x in ["myself", "only me", "just me"]):
        satisfied.append("group_size_checked")
    if any(x in q_lower for x in ["group", "party", "gathering", "people"]):
        satisfied.append("group_size_checked")

    # Persist conversation state
    save_conversation_state(state["conversation_id"], conv_state)

    return {**state, "tool_results": tool_results, "conversation_state": conv_state}


# ─────────────────────────────────────────────
# Node: build_response
# ─────────────────────────────────────────────

def node_build_response(state: AgentState) -> AgentState:
    conv_state = state.get("conversation_state", {})
    suggestions_shown = conv_state.get("suggestions_shown", [])

    composite_prompt = build_composite_prompt(
        query=state["query"],
        retrieved_chunks=state["retrieved_chunks"],
        customer_context=state["customer_context"],
        global_stats=state["global_stats"],
        tool_results=state["tool_results"],
        conversation_history=state["history"],
        business_name=state["business_name"],
        business_type=state["business_type"],
        detected_intents=state.get("detected_intents", []),
        conversation_state=conv_state,
    )

    response = llm_call(composite_prompt, temperature=0.5, max_tokens=800)
    
    # ── Upsell Throttling Logic ──
    # Track items already suggested to the user to prevent repetition
    upsell_match = re.search(r"(?i)would you like to (?:add|book|include|try)\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)", response)
    if upsell_match:
        item = upsell_match.group(1).strip()
        if item not in suggestions_shown:
            suggestions_shown.append(item)
            conv_state["suggestions_shown"] = suggestions_shown
            save_conversation_state(state["conversation_id"], conv_state)
    
    
    # FINAL SANITIZATION: Ensure NO "Service X" leaks into human chat
    # This acts as a safety barrier even if RAG or previous tool outputs used them.
    sanitized = response
    if "Service" in response:
        conn = sqlite3.connect(os.getenv("DB_NAME", "business_agent.db"))
        conn.row_factory = sqlite3.Row
        try:
            for match in re.findall(r'Service\s+(\d+)', response):
                s_id = int(match)
                row = conn.execute("SELECT name FROM services WHERE id = ?", (s_id,)).fetchone()
                if row:
                    sanitized = sanitized.replace(f"Service {s_id}", f"**{row['name']}**")
        except Exception:
            pass
        finally:
            conn.close()

    log_message(state["conversation_id"], "assistant", sanitized)
    log_agent_event(
        state["conversation_id"],
        "response_generated",
        {
            "retrieved_chunks": len(state["retrieved_chunks"]),
            "activated_tools": state["activated_tools"],
            "detected_intents": state.get("detected_intents", []),
            "response_length": len(sanitized),
        },
    )
    return {**state, "response": sanitized}


# ─────────────────────────────────────────────
# Node: critic  (validates response against PDF rules)
# ─────────────────────────────────────────────

def node_critic(state: AgentState) -> AgentState:
    """
    Fast rule-based critic — no LLM call.
    Validates the response against basic quality rules instantly.
    Only regenerates if the response is clearly broken/empty.
    """
    response = state["response"]
    query = state["query"]
    intents = state.get("detected_intents", [])
    tool_results = state.get("tool_results", {})

    issues = []

    # Rule 1: Non-empty meaningful response
    if not response or len(response.strip()) < 15:
        issues.append("Response is too short or empty")

    # Rule 2: If confirm_order ran and succeeded, response should mention confirmation
    if "confirm_order" in tool_results:
        res = tool_results["confirm_order"]
        if res.get("success") and not any(
            w in response.lower() for w in ["confirm", "order", "total", "✅", "placed"]
        ):
            issues.append("Order confirmed but response doesn't acknowledge it")

    # Rule 3: If add_to_cart ran and succeeded, response should acknowledge item
    if "add_to_cart" in tool_results:
        res = tool_results["add_to_cart"]
        if res.get("success") and not any(
            w in response.lower() for w in ["added", "cart", "order", "got it", "sure"]
        ):
            issues.append("Item added but response doesn't acknowledge")

    # Rule 4: Response should not be a raw JSON dump (programming error)
    if response.strip().startswith('{') and response.strip().endswith('}'):
        issues.append("Response looks like raw JSON — not customer-facing")

    passed = len(issues) == 0
    critic_result = {
        "passed": passed,
        "score": 9 if passed else 4,
        "issues": issues,
        "method": "rule_based",
    }
    log_agent_event(state["conversation_id"], "critic_review", critic_result)

    # Only do LLM regeneration for truly broken responses
    if not passed and "Response is too short or empty" in issues:
        try:
            fix_prompt = f"""The agent response was empty or broken. Generate a proper response.

Customer query: "{query}"
Tool results: {json.dumps({k: v.get('message', '') for k, v in tool_results.items()}, default=str)}

Write a helpful, conversational response:"""
            fixed = llm_call(fix_prompt, temperature=0.4, max_tokens=400)
            log_message(state["conversation_id"], "assistant_revised", fixed)
            log_agent_event(state["conversation_id"], "critic_revision", {"issues": issues})
            return {**state, "response": fixed, "critic_passed": True, "critic_feedback": "Revised: was empty"}
        except Exception:
            pass

    return {
        **state,
        "critic_passed": passed,
        "critic_feedback": json.dumps(issues),
    }


# ─────────────────────────────────────────────
# Build the Graph
# ─────────────────────────────────────────────

def build_graph() -> StateGraph:
    """
    Optimised graph: 4 nodes instead of 7.

    Old flow (7 nodes, 6+ LLM calls/turn):
      receive_input → detect_intents → rag_retrieval → planner
      → route_tools → execute_tools → build_response → critic

    New flow (4 nodes, 3 LLM calls/turn):
      receive_input → rag_retrieval → analyze(intents+plan+tools)
      → execute_tools → build_response → critic(rule-based)
    """
    graph = StateGraph(AgentState)

    graph.add_node("receive_input", node_receive_input)
    graph.add_node("rag_retrieval", node_rag_retrieval)   # LLM call #1: topic extraction
    graph.add_node("analyze", node_analyze)               # LLM call #2: intents+plan+tools
    graph.add_node("execute_tools", node_execute_tools)
    graph.add_node("build_response", node_build_response) # LLM call #3: final response
    graph.add_node("critic", node_critic)                 # rule-based: no LLM call

    graph.set_entry_point("receive_input")
    graph.add_edge("receive_input", "rag_retrieval")
    graph.add_edge("rag_retrieval", "analyze")
    graph.add_edge("analyze", "execute_tools")
    graph.add_edge("execute_tools", "build_response")
    graph.add_edge("build_response", "critic")
    graph.add_edge("critic", END)

    return graph.compile()


# ─────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────

_compiled_graph = None


def get_agent():
    global _compiled_graph
    if _compiled_graph is None:
        _compiled_graph = build_graph()
    return _compiled_graph


def run_agent_turn(
    user_id: int,
    conversation_id: str,
    query: str,
    all_chunks: list[dict],
    business_name: str,
    business_type: str,
) -> str:
    agent = get_agent()
    initial_state: AgentState = {
        "user_id": user_id,
        "conversation_id": conversation_id,
        "query": query,
        "history": [],
        "all_chunks": all_chunks,
        "retrieved_chunks": [],
        "retrieved_chunk_ids": [],
        "query_topics": [],
        "detected_intents": [],
        "customer_context": {},
        "global_stats": {},
        "tool_results": {},
        "activated_tools": [],
        "response": "",
        "critic_passed": True,
        "critic_feedback": "",
        "business_name": business_name,
        "business_type": business_type,
        "internal_plan": "",
        "conversation_state": {},
    }
    final_state = agent.invoke(initial_state)
    return final_state["response"]
